version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
       - checkout 
       - run:
          name: The First Step
          command: gradle test
       - store_test_results:
          path: build/test-results
       - store_artifacts:
          path: build/test-results
          destination: prefix
     workflows:
          version: 2
          two_job_flow:
    jobs:
       - job-1
       - job-2
          #echo 'Hello World!'
            #echo 'This is the delivery pipeline'
