version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
       - checkout 
       - run:
          name: The First Step
          command: gradle test
       - store_test_results:
          path: build/test-results
       - store_artifacts:
          path: build/test-results
          destination: prefix
 version: 2
jobs:
 dockerize:
   machine: true
   steps:
     - checkout
     # Login to docker
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .

     # deploy the image
     - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1
          #echo 'Hello World!'
            #echo 'This is the delivery pipeline'
